@startuml components
skinparam monochrome true
skinparam shadowing false
skinparam backgroundColor transparent
skinparam classBackgroundColor transparent
skinparam style strictuml

database "Git Repositories" as GitRepos
database "PostgreSQL DB" as Postgres

() "HTTP Endpoint" as HTTP

component "Application Container" {
  component Server
  HTTP -- Server
  package "Route Handlers" {
    component "Git Upload" as GitUpload
    component "REST" as REST
    component "GraphQL" as GraphQL
    GraphQL <.left. REST
  }
  component Loaders
  component "Git DAL" as GitDAL

  Server .down.> GitUpload
  GitUpload .right.> GitRepos
  Server .down.> GraphQL
  Server .down.> REST
  GraphQL .down.> Loaders
  Loaders .down..> Postgres
  Loaders .down.> GitDAL
  GitDAL ..> GitRepos
}

@enduml
