@startuml components
skinparam monochrome true
skinparam shadowing false
skinparam backgroundColor transparent
skinparam classBackgroundColor transparent


database "Git Repositories" as GitRepos
database "PostgreSQL DB" as Postgres

() "HTTP Endpoint" as HTTP

component "Application Container" {
  component Server
  HTTP -- Server
  package "Routes" {
    component "Git Upload" as GitUpload
    component "REST" as REST
    component "GraphQL" as GraphQL
  }
  component Loaders
  component "Git DAL" as GitDAL

  Server .down.> GitUpload
  GitUpload .right.> GitRepos
  Server .down.> GraphQL
  Server .down.> REST
  REST .down.> Loaders
  GraphQL .down.> Loaders
  Loaders .down..> Postgres
  Loaders .down.> GitDAL
  GitDAL ..> GitRepos
}

@enduml
