@startuml database
hide circle
hide empty members
skinparam monochrome true
skinparam style strictuml
skinparam shadowing false
skinparam backgroundColor transparent
skinparam classBackgroundColor transparent

entity code_smell_lifespans {
  *id UUID <<PK>>
  *kind TEXT
  *repository TEXT
  *analysis UUID <<FK>>
}

entity code_smells {
  *id UUID <<PK>>
  *lifespan UUID <<FK>>
  *ordinal INTEGER
  *commit TEXT
  *locations JSONB
  message TEXT
}

code_smells }|--|| code_smell_lifespans

entity analyses {
  *id UUID <<PK>>
  *name TEXT
}
code_smells }o--|| analyses

entity analysed_commits {
  *analysis UUID
  *repository TEXT
  *commit TEXT
}

analyses ||--o{ analysed_commits

' entity file_links {
'   *from_path TEXT
'   *from_commit TEXT
'   *from_start_line INTEGER
'   *from_end_line INTEGER
'   *from_start_character INTEGER
'   *from_end_character INTEGER
'   *to_path TEXT
'   *to_commit TEXT
'   *to_start_line INTEGER
'   *to_end_line INTEGER
'   *to_start_character INTEGER
'   *to_end_character INTEGER
' }

@enduml
