@startuml database_normalized
hide circle
hide empty members
skinparam monochrome true
skinparam style strictuml
skinparam shadowing false
skinparam backgroundColor transparent
skinparam classBackgroundColor transparent

entity code_smell_lifespans {
  *id UUID <<PK>>
  *kind TEXT
  *repository TEXT
  *analysis UUID <<FK>>
}

entity code_smells {
  *id INTEGER <<PK>>
  *lifespan UUID <<FK>>
  *ordinal INTEGER
  *commit TEXT
  message TEXT
}

entity code_smell_locations {
  *code_smell INTEGER <<FK>>
  *file TEXT
  *start_line INTEGER
  *start_character INTEGER
  *end_line INTEGER
  *end_character INTEGER
}

code_smells ||-|{ code_smell_locations

code_smell_lifespans ||-|{ code_smells

entity analyses {
  *id UUID <<PK>>
  *name TEXT
}
analyses ||--o{ code_smell_lifespans

entity analyzed_commits {
  *analysis UUID
  *repository TEXT
  *commit TEXT
}

analyses ||-o{ analyzed_commits

@enduml
